server:
  port: 9912
spring:
  config:
    import: nacos:gateway.yml,nacos:kubo-gateway-value.yml
  application:
    name: kubo-gateway
  profiles:
    active: value,formal,private
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: 172.23.104.184
      config:
        server-addr: 172.23.104.184
        file-extension: yml
        username: nacos
        password: nacos
