server:
  port: 9912

spring:
  application:
    name: kubo-gateway
  profiles:
    active: value,formal,private
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    nacos:
      discovery:
        server-addr: z32n237735.wicp.vip:33486
      config:
        server-addr: z32n237735.wicp.vip:33486
        import-check:
          enabled: false
