server:
  port: 8081

  #============================================================================
  # netty socket io setting
  #============================================================================
  # host在本地测试可以设置为localhost或者本机IP，在Linux服务器跑可换成服务器IP
socketio:
  host: 127.0.0.1
  port: 9099
  # 设置最大每帧处理数据的长度，防止他人利用大数据来攻击服务器
  maxFramePayloadLength: 1048576
  # 设置http交互最大内容长度
  maxHttpContentLength: 1048576
  # socket连接数大小（如只监听一个端口boss线程组为1即可）
  bossCount: 1
  workCount: 100
  allowCustomRequests: true
  # 协议升级超时时间（毫秒），默认10秒。HTTP握手升级为ws协议超时时间
  upgradeTimeout: 1000000
  # Ping消息超时时间（毫秒），默认60秒，这个时间间隔内没有接收到心跳消息就会发送超时事件
  pingTimeout: 6000000
  # Ping消息间隔（毫秒），默认25秒。客户端向服务器发送一条心跳消息间隔
  pingInterval: 25000
  enventName: "thermal_alarm"

detect:
#  enginePath: /opt/LnxReleaseFiles/libVtVca.so.4.8.11.0
#  enginePath: /opt/LnxReleaseFiles/libVtVca.so.4.10.0.0
  enginePath: /home/xzhou/Demo/ReleaseFiles/libVtVcaJetson.so.4.10.1.0
#  enginePath: /data/application/resource/ThermalDetect/libVtVcaJetson.so.4.10.1.0
#  enginePath: D:\code\xiangmu\ThermalDetect\src\main\resources\detectEngine\debug\VtVca.dll
#  enginePath: D:\code\xiangmu\ThermalDetect\target\classes\detectEngine\release\VtVca.dll

  imagePath: /opt/alarmImages/
#  imagePath: D:\456\

#logging:
#  #level 日志等级 指定命名空间的日志输出
#  level:
#    com.enbo.log: debug
#  #file 指定输出文件的存储路径
#  file: logs/log.log
#  #pattern 指定输出场景的日志输出格式
#  pattern:
#    console: "%d %-5level %logger : %msg%n"
#    file: "%d %-5level [%thread] %logger : %msg%n"

spring:
  profiles:
    active: prod

logging:
  level:
    org.apache.http.wire: INFO
  config: classpath:log4j.properties