
server:
  port: 8082

#trace=true


#spring.task.execution.pool.core-size=10
#
#spring.task.scheduling.pool.size=2

spring:
  datasource:
    driver-class-name: com.taosdata.jdbc.rs.RestfulDriver
    url: jdbc:TAOS-RS://192.168.1.165:6041/test2?user=root&password=taosdata&batchfetch=true
    # using connection pools
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml

mystarter:
  message: Hello from My Starter!
