global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  - minio-alerting.yml
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: minio-job
    bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJleHAiOjQ4MjI4Nzk0NDgsImlzcyI6InByb21ldGhldXMiLCJzdWIiOiJtaW5pb2FkbWluIn0.pm7zmjWUnaRkr2onz_Zw10ExwNk4dF0SAh3mW0-z70y1Kd3gM8pnEZB4RxNDJHSkQzL1wTDoG9uMSOxFS_f6iw
    metrics_path: /minio/v2/metrics/cluster
    scheme: http
    static_configs:
    - targets: ['192.168.1.176:9000']
